# Generated by Django 4.2.30 on 2026-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('guest', 'Guest')], default='guest', max_length=32),
        ),
    ]
