# Generated by Django 4.2.30 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_guest_remove_reservation_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.CharField(default='booking/images/room-default.svg', max_length=250),
        ),
    ]
