# Generated by Django 6.0.6 on 2026-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50)),
                ('policy_holder', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
